# Generated by Django 5.0.6 on 2024-05-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('email', models.CharField(max_length=100, verbose_name='Електронна пошта')),
                ('phone_num', models.CharField(blank=True, max_length=13, verbose_name='Номер телефону*')),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('s_last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('s_phone_num', models.CharField(max_length=13, verbose_name='Номер телефону')),
                ('work_experience', models.CharField(max_length=2, verbose_name='Стаж роботи (років)')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.CharField(max_length=3, verbose_name='Номер столику')),
                ('capacity', models.CharField(max_length=2, verbose_name='Вмістимість')),
                ('date', models.DateTimeField(verbose_name='Дата бронювання')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='main.client', verbose_name='Клієнт')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='main.servant', verbose_name='Офіціант')),
            ],
        ),
    ]
